///<reference types="cypress"/>

describe('SproutSmokeTest_QA',()=>{
    beforeEach(() => {
        // Cypress starts out with a blank slate for each test
        // so we must tell it to visit our website with the `cy.visit()` command.
        // Since we want to visit the same URL at the start of all our tests,
        // we include it in our beforeEach function so that it runs before each test
        cy.viewport('macbook-13')
        cy.visit('https://app-qa.getsprout.co/')
      })
    
    it('1.2 Try to Sign Up and request a demo',()=>{
        cy.contains('Sign up').click()
        cy.url().should('contains','join')
        cy.get('#name').type('TestFromMike')
        cy.wait(500)
        cy.get('#email').type('TestFromMike')
        cy.wait(500) 
        cy.get('#title').type('Mike_1983')
        cy.wait(500)
        cy.contains('Email address is invalid.').should('be.exist')
        cy.get('#company').type('TestCompany')
        cy.wait(500)
        cy.get('#share').type('TestFromMike')
        cy.wait(500)
        cy.get('#answer')
          .type('TestFromMike')
        cy.wait(500)
        cy.go('back')
        cy.contains('Request a Demo')
          .click()
        cy.url().should('contains','requestdemo')
        cy.get('#name')
          .type('TestFromMike')
        cy.wait(500)
        cy.get('#email').type('TestFromMike')
        cy.wait(500)
        cy.get('#title').type('Mike_1983')
        cy.contains('Email address is invalid.').should('be.exist')
        cy.wait(500)
        cy.get('#company').type('TestCompany')
        cy.wait(500)
        cy.get('#share').type('TestFromMike')
        cy.wait(500)
        cy.get('#answer').type('TestFromMike')
        cy.contains('This field must be number')
          .should('be.exist')
        cy.wait(500)
        cy.get('#request_demo').click()
        cy.contains('Successed!')
          .should('be.exist') 
        cy.clearCookies()
        cy.getCookies().should('be.empty')
      })
})
